### ISSUE TITLE
get() method not working

### ISSUE THREAD

**Issue by mmiladi** [bgruening/galaxy-ipython#35]
Hi,
This extension is really cool! There seems to be some problem with reading the input data. Please check the attached screen-shot.

![screenshot from 2017-07-11 16-07-01](https://user-images.githubusercontent.com/6370737/28074301-7e5f1196-6658-11e7-9780-ea2d9972738c.png)

**Comment by bgruening** [comment]
@mmiladi this is fixed on galaxy.uni-freiburg.de

**Comment by mmiladi** [comment]
Thanks @bgruening
